document.addEventListener('DOMContentLoaded', function () {
  document.querySelector("#reset").addEventListener('click',reset);
});

function reset(){
  chrome.storage.sync.clear();
  idf("money-text").innerHTML = 0;
  idf("childrens-stats").innerHTML = 0;
  idf("drama-stats").innerHTML = 0;
  idf("fantasy-stats").innerHTML = 0;
  idf("fiction-stats").innerHTML = 0;
  idf("history-stats").innerHTML = 0;
  idf("scifi-stats").innerHTML = 0;
  idf("trashy-stats").innerHTML = 0;
  idf("nonfiction-stats").innerHTML = 0;
  idf("math-stats").innerHTML = 0;
  idf("humor-stats").innerHTML = 0;
  idf("satire-stats").innerHTML = 0;
  idf("romance-stats").innerHTML = 0;
  idf("report-stats").innerHTML = 0;
  idf("survival-stats").innerHTML = 0;
  idf("gothic-stats").innerHTML = 0;
  idf("adventure-stats").innerHTML = 0;
  idf("action-stats").innerHTML = 0;
  idf("environmental-stats").innerHTML = 0;
  idf("parenting-stats").innerHTML = 0;
  idf("religious-stats").innerHTML = 0;
  var fantasy = idf("fantasy");
  fantasy.innerHTML = "Locked ???";
  fantasy.className = "book-button-locked";
  var satire = idf("satire");
  satire.innerHTML = "Locked ???";
  satire.className = "book-button-locked";
  var history = idf("history");
  history.innerHTML = "Locked 1500$";
  history.value = 0;
  history.className = "book-button-locked";
  var trashy = idf("trashy");
  trashy.innerHTML = "Locked 1000$";
  trashy.value = 0;
  trashy.className = "book-button-locked";
  var action = idf("action");
  action.innerHTML = "Locked 6000$";
  action.value = 0;
  action.className = "book-button-locked";
  var romance = idf("romance");
  romance.innerHTML = "Locked 3000$";
  romance.value = 0;
  romance.className = "book-button-locked";
  var environmental = idf("environmental");
  environmental.innerHTML = "Locked 12000$";
  environmental.value = 0;
  environmental.className = "book-button-locked";
  var parenting = idf("parenting");
  parenting.innerHTML = "Locked 15000$";
  parenting.value = 0;
  parenting.className = "book-button-locked";
  var religious = idf("religious");
  religious.innerHTML = "Locked 20000$";
  religious.value = 0;
  religious.className = "book-button-locked";
}