name: book-game
version: 0.1.0
description: A book making game for chrome os
author: dragonloverlord
homepage: https://github.com/dragonloverlord/book-game
documentation: https://github.com/dragonloverlord/book-game/wiki
dependencies:
  chrome: any
  polymer: "^0.16.3+3"
  angular: "^1.1.2"
transformers:
- polymer:
    entry_points:
    - ./web/index.html
    csp: true
- $dart2js:
    csp: true
    minify: true
